name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image for Server
        run: |
          docker build -f server/Dockerfile -t hjain2003/lambdaserver:latest .

      - name: Push Docker Image for Server
        run: |
          docker push hjain2003/lambdaserver:latest

      - name: Build Docker Image for Client
        run: |
          docker build -f client/Dockerfile -t hjain2003/lambdaclient:latest .

      - name: Push Docker Image for Client
        run: |
          docker push hjain2003/lambdaclient:latest